// ivf-web/src/app/features/iui/iui-list/iui-list.component.ts
import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { DatePipe } from '@angular/common';
import { Router } from '@angular/router';
import { Store } from '@ngrx/store';
import { Subject, combineLatest } from 'rxjs';
import { filter, switchMap, takeUntil } from 'rxjs/operators';
import { IuiListRow, IuiService } from '../../../core/services/iui.service';
import { selectAuthToken } from '../../../store/auth/auth.selectors';
import { selectPatientWithSatellite } from '../../../store/patient/patient.selectors';

@Component({
  selector: 'app-iui-list',
  standalone: true,
  imports: [DatePipe],
  templateUrl: './iui-list.component.html',
  styleUrl: './iui-list.component.scss',
})
export class IuiListComponent implements OnInit, OnDestroy {
  private store = inject(Store);
  private iuiService = inject(IuiService);
  private router = inject(Router);
  private destroy$ = new Subject<void>();

  rows: IuiListRow[] = [];
  loading = false;
  error = '';
  success = '';
  patientName = '';

  ngOnInit(): void {
    combineLatest([
      this.store.select(selectAuthToken).pipe(filter((token): token is string => !!token)),
      this.store.select(selectPatientWithSatellite).pipe(filter((patient) => !!patient && !!patient.satelliteId)),
    ])
      .pipe(
        switchMap(([token, patient]) => {
          this.patientName = patient!.name;
          this.loading = true;
          this.error = '';
          return this.iuiService.list(token, patient!.id, patient!.satelliteId);
        }),
        takeUntil(this.destroy$)
      )
      .subscribe({
        next: (res) => {
          this.rows = res.data || [];
          this.loading = false;
        },
        error: (err) => {
          this.error = err?.error?.message || 'Failed to load IUI list.';
          this.loading = false;
        },
      });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  addNew(): void {
    this.router.navigate(['/iui/new']);
  }

  selectRow(row: IuiListRow): void {
    const iuiOId = Number(row.IUIOID ?? row['IUIOID']);
    this.router.navigate(['/iui', row.IUIID], { queryParams: { iuiOId } });
  }

  deleteRow(row: IuiListRow): void {
    const iuiOId = Number(row.IUIOID ?? row['IUIOID']);
    this.router.navigate(['/iui', row.IUIID], { queryParams: { iuiOId, mode: 'delete' } });
  }

  unlockRow(row: IuiListRow): void {
    combineLatest([
      this.store.select(selectAuthToken).pipe(filter((token): token is string => !!token)),
      this.store.select(selectPatientWithSatellite).pipe(filter((patient) => !!patient && !!patient.satelliteId)),
    ])
      .pipe(takeUntil(this.destroy$))
      .subscribe(([token, patient]) => {
        this.iuiService
          .unlock(token, { patId: patient!.id, cycleId: row.IUIID, patName: patient!.name })
          .subscribe({
            next: (res) => {
              this.success = res.message;
              this.reload(token, patient!.id, patient!.satelliteId);
            },
            error: (err) => {
              this.error = err?.error?.message || 'Failed to unlock cycle.';
            },
          });
      });
  }

  isLocked(row: IuiListRow): boolean {
    const value = row.IsLock ?? row['IsLock'];
    return value === true || value === 1 || value === '1' || value === 'True';
  }

  private reload(token: string, patId: number, satId: number): void {
    this.loading = true;
    this.iuiService.list(token, patId, satId).subscribe({
      next: (res) => {
        this.rows = res.data || [];
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      },
    });
  }
}

<div class="module-page">
  <div class="module-card">
    <div class="toolbar">
      <h1>IUI List of Patient</h1>
      <button type="button" class="btn-primary" (click)="addNew()">Add New</button>
    </div>

    @if (error) {
      <p class="error">{{ error }}</p>
    }
    @if (success) {
      <p class="success">{{ success }}</p>
    }

    @if (loading) {
      <p class="muted">Loading IUI records…</p>
    } @else {
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Action</th>
              <th>IUI Id</th>
              <th>IUI Indication</th>
              <th>IUI Date</th>
              <th>IUI Id Off</th>
              <th>Post Treatment</th>
              <th>Advice</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @for (row of rows; track row.IUIID) {
              <tr>
                <td><button type="button" class="link" (click)="selectRow(row)">Select</button></td>
                <td>{{ row.IUIID }}</td>
                <td>{{ row.Indication || '—' }}</td>
                <td>{{ row.IUIODateOfCreation | date:'dd-MMM-yyyy' }}</td>
                <td>{{ row.IUIIDOff || '—' }}</td>
                <td class="wide">{{ row.IUIOPostTreat || '—' }}</td>
                <td class="wide">{{ row.IUIOAdvice || '—' }}</td>
                <td><button type="button" class="link danger" (click)="deleteRow(row)">Delete</button></td>
                <td>
                  @if (isLocked(row)) {
                    <button type="button" class="link" (click)="unlockRow(row)">Unlock</button>
                  }
                </td>
              </tr>
            } @empty {
              <tr>
                <td colspan="9" class="empty">No IUI records found for this patient.</td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }
  </div>
</div>

// ivf-next/src/components/iui-list.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { ModuleAlerts, ModuleCard, PatientRequired, usePatientIds } from '@/components/clinical/clinical-shared';
import { useAuth } from '@/contexts/auth-context';
import { ApiError } from '@/lib/api';
import { asBool } from '@/lib/services/clinical-modules';
import { IuiListRow, listIui, unlockIui } from '@/lib/services/iui';

function formatDate(value: string | undefined): string {
  if (!value) return '—';
  return new Date(value).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

export function IuiList() {
  const router = useRouter();
  const { token } = useAuth();
  const { patId, satId, patientName, ready } = usePatientIds();
  const [rows, setRows] = useState<IuiListRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  const load = useCallback(async () => {
    if (!token || !ready) return;
    setLoading(true);
    setError('');
    try {
      setRows(await listIui(token, patId, satId));
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Failed to load IUI list.');
    } finally {
      setLoading(false);
    }
  }, [token, ready, patId, satId]);

  useEffect(() => {
    void load();
  }, [load]);

  async function handleUnlock(row: IuiListRow) {
    if (!token) return;
    setError('');
    setSuccess('');
    try {
      const res = await unlockIui(token, { patId, cycleId: row.IUIID, patName: patientName });
      setSuccess(res.message);
      await load();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Failed to unlock cycle.');
    }
  }

  return (
    <PatientRequired>
      <ModuleCard title="IUI List of Patient">
        <div className="mb-4 flex items-center justify-between gap-3">
          <p className="text-sm text-slate-600">Patient: {patientName}</p>
          <Link
            href="/iui/new"
            className="rounded-lg bg-brand-primary px-4 py-2 text-sm font-semibold text-white hover:bg-brand-dark"
          >
            Add New
          </Link>
        </div>

        <ModuleAlerts error={error} success={success} />

        {loading ? (
          <p className="text-sm text-slate-500">Loading IUI records…</p>
        ) : (
          <div className="overflow-x-auto rounded-lg border border-slate-200">
            <table className="min-w-full text-sm">
              <thead className="bg-slate-50 text-left text-xs uppercase text-slate-500">
                <tr>
                  <th className="px-3 py-2">Action</th>
                  <th className="px-3 py-2">IUI Id</th>
                  <th className="px-3 py-2">Indication</th>
                  <th className="px-3 py-2">IUI Date</th>
                  <th className="px-3 py-2">IUI Id Off</th>
                  <th className="px-3 py-2">Post Treatment</th>
                  <th className="px-3 py-2">Advice</th>
                  <th className="px-3 py-2"></th>
                  <th className="px-3 py-2"></th>
                </tr>
              </thead>
              <tbody>
                {(rows || []).map((row) => {
                  const iuiOId = Number(row.IUIOID ?? 0);
                  const locked = asBool(row.IsLock);
                  return (
                    <tr key={`${row.IUIID}-${iuiOId}`} className="border-t border-slate-100">
                      <td className="px-3 py-2">
                        <button
                          type="button"
                          onClick={() => router.push(`/iui/${encodeURIComponent(row.IUIID)}?iuiOId=${iuiOId}`)}
                          className="text-brand-primary hover:underline"
                        >
                          Select
                        </button>
                      </td>
                      <td className="px-3 py-2">{row.IUIID}</td>
                      <td className="px-3 py-2">{row.Indication || '—'}</td>
                      <td className="px-3 py-2">{formatDate(row.IUIODateOfCreation as string | undefined)}</td>
                      <td className="px-3 py-2">{row.IUIIDOff || '—'}</td>
                      <td className="max-w-xs px-3 py-2">{row.IUIOPostTreat || '—'}</td>
                      <td className="max-w-xs px-3 py-2">{row.IUIOAdvice || '—'}</td>
                      <td className="px-3 py-2">
                        <button
                          type="button"
                          onClick={() =>
                            router.push(`/iui/${encodeURIComponent(row.IUIID)}?iuiOId=${iuiOId}&mode=delete`)
                          }
                          className="text-red-600 hover:underline"
                        >
                          Delete
                        </button>
                      </td>
                      <td className="px-3 py-2">
                        {locked && (
                          <button type="button" onClick={() => void handleUnlock(row)} className="text-brand-primary hover:underline">
                            Unlock
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })}
                {!loading && (!rows || rows.length === 0) && (
                  <tr>
                    <td colSpan={9} className="px-3 py-6 text-center text-slate-500">
                      No IUI records found for this patient.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </ModuleCard>
    </PatientRequired>
  );
}
